# typed: strict
# frozen_string_literal: true

# Generated by packaging/generate.mjs — edit that script, not this file.
cask "harnessdeck" do
  version "0.1.0"

  # The release has no per-architecture Intel image since the artifacts were
  # slimmed to one format per platform, so Intel Macs install the universal
  # one while Apple silicon keeps its own.
  on_arm do
    url "https://github.com/duyanta123/HarnessDeck/releases/download/v#{version}/HarnessDeck_#{version}_aarch64.dmg"
    sha256 "e2198043e489d9eacaab6b48ecef86c4212a3c9c8169df1bde80b8c47b6c1587"
  end
  on_intel do
    url "https://github.com/duyanta123/HarnessDeck/releases/download/v#{version}/HarnessDeck_#{version}_universal.dmg"
    sha256 "9234272227dd6619934ef109a6c4bc100ce3e48cdb39e6c5e0c00a614d3daad4"
  end

  name "HarnessDeck"
  desc "Native desktop shell for DeepSeek Harness"
  homepage "https://github.com/duyanta123/HarnessDeck"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Tauri 2 supports Catalina and later. The binaries are tagged lower than that
  # — 11.0 on arm64, 10.13 on Intel — but the tag is the linker's deployment
  # target, not a claim that the webview underneath it works, so the framework's
  # floor is the one worth declaring.
  depends_on macos: ">= :catalina"

  app "HarnessDeck.app"

  # The application's own directory is named after the binary rather than the
  # bundle identifier, because it comes from the cross-platform data path and not
  # from Tauri. It holds the harness and any Node runtime the app downloaded, so
  # it is by far the largest thing to reclaim — a few hundred megabytes.
  #
  # ~/.dsh is deliberately absent. The harness owns that directory and shares it
  # with its own CLI, so removing it here would take a user's harness
  # configuration with an app they merely stopped using.
  zap trash: [
    "~/Library/Application Support/harnessdeck",
    "~/Library/Caches/app.harnessdeck",
    "~/Library/HTTPStorages/app.harnessdeck",
    "~/Library/Preferences/app.harnessdeck.plist",
    "~/Library/Saved Application State/app.harnessdeck.savedState",
    "~/Library/WebKit/app.harnessdeck",
  ]
end
